// Generated by CoffeeScript 1.12.4
var component;

component = { template: "<h1 :id=\"id\" @click=\"hi\">hello</h1><input type=\"text\">",
  data: function() {
    return [2, 4, 6, 8];
  }
};

var component$1 = component;

export default component$1;